CREATE TABLE IF NOT EXISTS ADDRESS
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    line_one VARCHAR(255) NOT NULL,
    line_two VARCHAR(255),
    city VARCHAR(255),
    county VARCHAR(255),
    post_code VARCHAR(255),
    country VARCHAR(255)
);

CREATE SEQUENCE address_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999
CYCLE;
