CREATE TABLE IF NOT EXISTS PHONE_NUMBER
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    country_code VARCHAR(255) NOT NULL,
    number VARCHAR(255),
    contact_id BIGINT
);

CREATE SEQUENCE phone_number_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999
CYCLE;