CREATE TABLE IF NOT EXISTS CONTACT
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    address_id BIGINT,
    phone_numbers_id BIGINT,
    contact_type VARCHAR(255)
);

CREATE SEQUENCE contact_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999
CYCLE;