CREATE TABLE IF NOT EXISTS PERSONAL
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    contact_id BIGINT NOT NULL
);

CREATE SEQUENCE personal_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999
CYCLE;